# `sudo:false` for faster builds.
sudo: false
language: node_js
env:
  - OX_PROJECT=tutor
  - OX_PROJECT=exercises
  - OX_PROJECT=shared
script:
  - npm run ci
after_failure:
  - npm list
after_success:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
  # Report to coveralls
  - cat ./coverage/*/lcov.info | node ./node_modules/.bin/coveralls --verbose
