# `sudo:false` for faster builds.
sudo: false
language: node_js
env:
  - OX_PROJECT=tutor
  - OX_PROJECT=exercises
  - OX_PROJECT=shared

addons:
  apt:
    packages:
      - shellcheck
      # For building kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

# Cache the 3rd-party packages. From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # Build https://github.com/SimonKagstrom/kcov (shell code coverage)
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    rm master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    rm -rf kcov-master
script: kcov ./coverage/ ./script/ci

after_failure:
  - npm list
after_success:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
  # Report to coveralls
  - cat ./coverage/*/lcov.info | node ./node_modules/.bin/coveralls --verbose
