version: '3.5'
services:
  tutor-js:
    command: bash -c "if [ -z \"`ls -A node_modules`\" ]; then yarn; fi && yarn serve tutor"
    build: .
    working_dir: /code
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "8000:8000"

